name: contador_pasos
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  decimal: ^3.0.2
  pedometer: ^4.0.2
  percent_indicator: ^4.2.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/step.png"


flutter:

  uses-material-design: true
  assets:
        - assets/images/
